<?php

namespace Database\Seeders;

use App\Models\Config;
use Illuminate\Database\Seeder;

class ConfigSeeder extends Seeder
{
    private array $configs = [
        'account_expire_notification',
        'active_times',
        'admin_invite_days',
        'aff_salt',
        'alipay_qrcode',
        'AppStore_id',
        'AppStore_password',
        'auto_release_port',
        'bark_key',
        'bitpay_secret',
        'captcha_key',
        'captcha_secret',
        'codepay_id',
        'codepay_key',
        'codepay_url',
        'data_anomaly_notification',
        'data_exhaust_notification',
        'ddns_key',
        'ddns_mode',
        'ddns_secret',
        'default_days',
        'default_traffic',
        'detection_check_times',
        'dingTalk_access_token',
        'dingTalk_secret',
        'epay_key',
        'epay_mch_id',
        'epay_url',
        'expire_days',
        'f2fpay_app_id',
        'f2fpay_private_key',
        'f2fpay_public_key',
        'forbid_mode',
        'invite_num',
        'is_activate_account',
        'is_AliPay',
        'is_ban_status',
        'is_captcha',
        'is_checkin',
        'is_clear_log',
        'is_custom_subscribe',
        'is_email_filtering',
        'is_forbid_robot',
        'is_free_code',
        'is_invite_register',
        'is_otherPay',
        'is_push_bear',
        'is_QQPay',
        'is_rand_port',
        'is_register',
        'is_subscribe_ban',
        'is_traffic_ban',
        'is_WeChatPay',
        'iYuu_token',
        'maintenance_content',
        'maintenance_mode',
        'maintenance_time',
        'max_port',
        'max_rand_traffic',
        'min_port',
        'min_rand_traffic',
        'node_blocked_notification',
        'node_daily_notification',
        'node_offline_notification',
        'oauth_path',
        'offline_check_times',
        'password_reset_notification',
        'paybeaver_app_id',
        'paybeaver_app_secret',
        'payjs_key',
        'payjs_mch_id',
        'payment_confirm_notification',
        'payment_received_notification',
        'paypal_app_id',
        'paypal_client_id',
        'paypal_client_secret',
        'pushDeer_key',
        'pushplus_token',
        'rand_subscribe',
        'redirect_url',
        'referral_money',
        'referral_percent',
        'referral_status',
        'referral_traffic',
        'referral_type',
        'register_ip_limit',
        'reset_password_times',
        'reset_traffic',
        'server_chan_key',
        'standard_currency',
        'stripe_public_key',
        'stripe_secret_key',
        'stripe_signing_secret',
        'subject_name',
        'subscribe_ban_times',
        'subscribe_domain',
        'subscribe_max',
        'telegram_token',
        'tg_chat_token',
        'theadpay_key',
        'theadpay_mchid',
        'theadpay_url',
        'ticket_closed_notification',
        'ticket_created_notification',
        'ticket_replied_notification',
        'traffic_ban_time',
        'traffic_ban_value',
        'traffic_limit_time',
        'traffic_warning_percent',
        'trojan_license',
        'username_type',
        'user_invite_days',
        'v2ray_license',
        'v2ray_tls_provider',
        'webmaster_email',
        'website_analytics',
        'website_callback_url',
        'website_customer_service',
        'website_home_logo',
        'website_logo',
        'website_name',
        'website_security_code',
        'website_url',
        'web_api_url',
        'wechat_aid',
        'wechat_cid',
        'wechat_encodingAESKey',
        'wechat_qrcode',
        'wechat_secret',
        'wechat_token',
    ];

    public function run(): void
    { // 系统参数
        foreach ($this->configs as $config) {
            Config::insert(['name' => $config]);
        }

        $presetDates = [
            'invite_num' => 3,
            'is_register' => 1,
            'is_invite_register' => 2,
            'website_name' => 'ProxyPanel',
            'reset_password_times' => 3,
            'website_url' => config('app.url'),
            'active_times' => 3,
            'is_checkin' => 1,
            'min_rand_traffic' => 10,
            'max_rand_traffic' => 500,
            'traffic_limit_time' => 1440,
            'referral_traffic' => 1024,
            'referral_percent' => 0.2,
            'referral_money' => 100,
            'referral_status' => 1,
            'default_traffic' => 1024,
            'traffic_warning_percent' => 80,
            'expire_days' => 15,
            'reset_traffic' => 1,
            'default_days' => 7,
            'subscribe_max' => 3,
            'min_port' => 10000,
            'max_port' => 65535,
            'is_traffic_ban' => 1,
            'traffic_ban_value' => 10,
            'traffic_ban_time' => 60,
            'is_clear_log' => 1,
            'is_subscribe_ban' => 1,
            'subscribe_ban_times' => 20,
            'auto_release_port' => 1,
            'register_ip_limit' => 5,
            'detection_check_times' => 3,
            'user_invite_days' => 7,
            'admin_invite_days' => 7,
            'standard_currency' => 'CNY',
        ];

        foreach ($presetDates as $key => $value) {
            Config::whereName($key)->update(['value' => $value]);
        }
    }
}
