<?php

namespace Database\Seeders;

use App\Models\EmailFilter;
use Illuminate\Database\Seeder;

class EmailFilterSeeder extends Seeder
{
    private array $white = [ // 白名单 邮箱过滤列表
        'qq.com',
        '163.com',
        '126.com',
        '189.com',
        'sohu.com',
        'gmail.com',
        'outlook.com',
        'icloud.com',
    ];

    private array $black = [ // 黑名单 邮箱过滤列表
        'chacuo.com',
        '1766258.com',
        '3202.com',
        '4057.com',
        '4059.com',
        'a7996.com',
        'bccto.me',
        'bnuis.com',
        'chaichuang.com',
        'cr219.com',
        'cuirushi.org',
        'dawin.com',
        'jiaxin8736.com',
        'lakqs.com',
        'urltc.com',
        '027168.com',
        '10minutemail.net',
        '11163.com',
        '1shivom.com',
        'auoie.com',
        'bareed.ws',
        'bit-degree.com',
        'cjpeg.com',
        'cool.fr.nf',
        'courriel.fr.nf',
        'disbox.net',
        'disbox.org',
        'fidelium10.com',
        'get365.pw',
        'ggr.la',
        'grr.la',
        'guerrillamail.biz',
        'guerrillamail.com',
        'guerrillamail.de',
        'guerrillamail.net',
        'guerrillamail.org',
        'guerrillamailblock.com',
        'hubii-network.com',
        'hurify1.com',
        'itoup.com',
        'jetable.fr.nf',
        'jnpayy.com',
        'juyouxi.com',
        'mail.bccto.me',
        'www.bccto.me',
        'mega.zik.dj',
        'moakt.co',
        'moakt.ws',
        'molms.com',
        'moncourrier.fr.nf',
        'monemail.fr.nf',
        'monmail.fr.nf',
        'nomail.xl.cx',
        'nospam.ze.tc',
        'pay-mon.com',
        'poly-swarm.com',
        'sgmh.online',
        'sharklasers.com',
        'shiftrpg.com',
        'spam4.me',
        'speed.1s.fr',
        'tmail.ws',
        'tmails.net',
        'tmpmail.net',
        'tmpmail.org',
        'travala10.com',
        'yopmail.com',
        'yopmail.fr',
        'yopmail.net',
        'yuoia.com',
        'zep-hyr.com',
        'zippiex.com',
        'lrc8.com',
        '1otc.com',
        'emailna.co',
        'mailinator.com',
        'nbzmr.com',
        'awsoo.com',
        'zhcne.com',
        '0box.eu',
        'contbay.com',
        'damnthespam.com',
        'kurzepost.de',
        'objectmail.com',
        'proxymail.eu',
        'rcpt.at',
        'trash-mail.at',
        'trashmail.at',
        'trashmail.com',
        'trashmail.io',
        'trashmail.me',
        'trashmail.net',
        'wegwerfmail.de',
        'wegwerfmail.net',
        'wegwerfmail.org',
        'nwytg.net',
        'despam.it',
        'spambox.us',
        'spam.la',
        'mytrashmail.com',
        'mt2014.com',
        'mt2015.com',
        'thankyou2010.com',
        'trash2009.com',
        'mt2009.com',
        'trashymail.com',
        'tempemail.net',
        'slopsbox.com',
        'mailnesia.com',
        'ezehe.com',
        'tempail.com',
        'newairmail.com',
        'temp-mail.org',
        'linshiyouxiang.net',
        'zwoho.com',
        'mailboxy.fun',
        'crypto-net.club',
        'guerrillamail.info',
        'pokemail.net',
        'odmail.cn',
        'hlooy.com',
        'ozlaq.com',
        '666email.com',
        'linshiyou.com',
        'linshiyou.pl',
        'woyao.pl',
        'yaowo.pl',
    ];

    public function run(): void
    {
        foreach ($this->black as $emailSuffix) {
            EmailFilter::insert(['type' => 1, 'words' => $emailSuffix]);
        }

        foreach ($this->white as $emailSuffix) {
            EmailFilter::insert(['type' => 2, 'words' => $emailSuffix]);
        }
    }
}
