<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RBACSeeder extends Seeder
{
    private array $permissions = [
        'admin.aff.detail' => '【推广系统】提现申请详情',
        'admin.aff.index' => '【推广系统】提现管理列表',
        'admin.aff.rebate' => '【推广系统】返利流水记录',
        'admin.aff.setStatus' => '【推广系统】设置提现状态',
        'admin.article.create,store' => '【客服系统】新建文章',
        'admin.article.destroy' => '【客服系统】删除文章',
        'admin.article.edit,update' => '【客服系统】编辑文章',
        'admin.article.index,show' => '【客服系统】文章列表',
        'admin.config.*' => '【设置】通用配置',
        'admin.coupon.create,store' => '【商品系统】新建卡劵',
        'admin.coupon.destroy' => '【商品系统】删除卡劵',
        'admin.coupon.export' => '【商品系统】导出卡劵',
        'admin.coupon.index' => '【商品系统】卡劵列表',
        'admin.goods.create,store' => '【商品系统】新建商品',
        'admin.goods.destroy' => '【商品系统】删除商品',
        'admin.goods.edit,update' => '【商品系统】编辑商品',
        'admin.goods.index' => '【商品系统】商品列表',
        'admin.index' => '【管理中心】首页',
        'admin.invite.index' => '【推广系统】邀请列表',
        'admin.invite.create' => '【推广系统】生成邀请码',
        'admin.invite.export' => '【推广系统】导出邀请码',
        'admin.log.ban' => '【日志系统】封禁记录',
        'admin.log.credit' => '【日志系统】余额记录',
        'admin.log.flow' => '【日志系统】流量变动记录',
        'admin.log.ip' => '【日志系统】在线IP记录',
        'admin.log.notify' => '【日志系统】通知记录',
        'admin.log.online' => '【日志系统】在线监控',
        'admin.log.traffic' => '【日志系统】流量日志',
        'log-viewer::dashboard,log-viewer::logs.*' => '【日志系统】运行日志',
        'admin.marketing.add' => '【客服系统】推送消息',
        'admin.marketing.email' => '【客服系统】邮件消息列表',
        'admin.marketing.push' => '【客服系统】推送消息列表',
        'admin.node.auth.destroy' => '【线路系统】删除授权',
        'admin.node.auth.index' => '【线路系统】授权列表',
        'admin.node.auth.store' => '【线路系统】新建授权',
        'admin.node.auth.update' => '【线路系统】编辑授权',
        'admin.node.cert.create,store' => '【线路系统】新建证书',
        'admin.node.cert.destroy' => '【线路系统】删除证书',
        'admin.node.cert.edit,update' => '【线路系统】编辑证书',
        'admin.node.cert.index' => '【线路系统】证书列表',
        'admin.node.check' => '【线路系统】阻断检测',
        'admin.node.create,store' => '【线路系统】新建线路',
        'admin.node.destroy' => '【线路系统】删除线路',
        'admin.node.edit,update' => '【线路系统】编辑线路',
        'admin.node.geo' => '【线路系统】更新地理',
        'admin.node.index' => '【线路系统】线路列表',
        'admin.node.monitor' => '【线路系统】流量监控',
        'admin.node.ping' => '【线路系统】测速',
        'admin.node.reload' => '【线路系统】重载',
        'admin.order' => '【商品系统】订单列表',
        'admin.payment.callback' => '【日志系统】回调列表',
        'admin.permission.create,store' => '【权限系统】新建权限',
        'admin.permission.destroy' => '【权限系统】删除权限',
        'admin.permission.edit,update' => '【权限系统】编辑权限',
        'admin.permission.index' => '【权限系统】权限列表',
        'admin.role.create,store' => '【权限系统】新建角色',
        'admin.role.destroy' => '【权限系统】删除角色',
        'admin.role.edit,update' => '【权限系统】编辑角色',
        'admin.role.index' => '【权限系统】角色列表',
        'admin.rule.clear' => '【审计规则】清除触发日志',
        'admin.rule.destroy' => '【审计规则】删除规则',
        'admin.rule.group.assign,editNode' => '【审计规则】分组关联线路',
        'admin.rule.group.create,store' => '【审计规则】新建分组',
        'admin.rule.group.destroy' => '【审计规则】删除分组',
        'admin.rule.group.edit,update' => '【审计规则】编辑分组',
        'admin.rule.group.index' => '【审计规则】分组列表',
        'admin.rule.index' => '【审计规则】规则列表',
        'admin.rule.log' => '【审计规则】触发日志',
        'admin.rule.store' => '【审计规则】新建规则',
        'admin.rule.update' => '【审计规则】编辑规则',
        'admin.subscribe.index' => '【用户系统】订阅列表',
        'admin.subscribe.log' => '【用户系统】订阅记录',
        'admin.subscribe.set' => '【用户系统】编辑订阅状态',
        'admin.system.index' => '【设置】查看系统设置',
        'admin.system.update,extend' => '【设置】编辑系统设置',
        'admin.test.*' => '【设置】通知，支付设置测试',
        'admin.ticket.destroy' => '【客服系统】删除工单',
        'admin.ticket.edit,update' => '【客服系统】回复工单',
        'admin.ticket.index' => '【客服系统】工单列表',
        'admin.ticket.store' => '【客服系统】新建工单',
        'admin.tools.*' => '【工具箱】',
        'admin.user.batch' => '【用户系统】生成用户',
        'admin.user.create,store' => '【用户系统】新建用户',
        'admin.user.destroy' => '【用户系统】删除用户',
        'admin.user.edit,update' => '【用户系统】编辑用户',
        'admin.user.export' => '【用户系统】配置信息',
        'admin.user.exportProxy' => '【用户系统】读取配置',
        'admin.user.group.create,store' => '【用户系统】新建分组',
        'admin.user.group.destroy' => '【用户系统】删除分组',
        'admin.user.group.edit,update' => '【用户系统】编辑分组',
        'admin.user.group.index' => '【用户系统】分组列表',
        'admin.user.index' => '【用户系统】用户列表',
        'admin.user.monitor' => '【用户系统】流量统计',
        'admin.user.online' => '【用户系统】在线巡查',
        'admin.user.reset' => '【用户系统】流量重置',
        'admin.user.switch' => '【用户系统】用户视角',
        'admin.user.updateCredit' => '【用户系统】编辑余额',
        'give roles' => '【用户系统】赋予角色权限',
    ];

    public function run(): void
    {
        // RBAC
        Role::create(['name' => 'Super Admin', 'description' => '超级管理员']);
        foreach ($this->permissions as $name => $description) {
            Permission::insert(['name' => $name, 'description' => $description, 'guard_name' => 'web']);
        }
    }
}
