<?php

// 常见域名后缀
return [
    'com', 'net', 'org', 'couk', 'io', 'computer', 'ac', 'academy', 'actor', 'ae', 'aero', 'af', 'ag', 'agency',
    'ai', 'am', 'archi', 'arpa', 'as', 'asia', 'associates', 'at', 'au', 'aw', 'ax', 'az', 'bar', 'bargains', 'ltd',
    'bayern', 'be', 'berlin', 'bg', 'bi', 'bike', 'biz', 'bj', 'blackfriday', 'bn', 'boutique', 'build', 'builders',
    'bw', 'by', 'ca', 'cab', 'camera', 'camp', 'capital', 'cards', 'careers', 'cat', 'catering', 'cc', 'center', 'style',
    'ceo', 'cf', 'ch', 'cheap', 'christmas', 'ci', 'cl', 'cleaning', 'clothing', 'club', 'cn', 'co', 'codes', 'store',
    'coffee', 'college', 'cologne', 'community', 'company', 'construction', 'contractors', 'cooking', 'cool', 'online',
    'coop', 'country', 'cruises', 'cx', 'cz', 'dating', 'de', 'democrat', 'desi', 'diamonds', 'directory', 'dk', 'vip',
    'dm', 'domains', 'dz', 'ec', 'edu', 'education', 'ee', 'email', 'engineering', 'enterprises', 'equipment', 'top',
    'es', 'estate', 'eu', 'eus', 'events', 'expert', 'exposed', 'farm', 'feedback', 'fi', 'fish', 'fishing', 'dog',
    'flights', 'florist', 'fo', 'foo', 'foundation', 'fr', 'frogans', 'futbol', 'ga', 'gal', 'gd', 'gg', 'gi', 'fun',
    'gift', 'gl', 'glass', 'gop', 'gov', 'graphics', 'gripe', 'gs', 'guitars', 'guru', 'gy', 'haus', 'hk', 'hn', 'loans',
    'holiday', 'horse', 'house', 'hr', 'ht', 'hu', 'id', 'ie', 'il', 'im', 'immobilien', 'in', 'industries', 'holdings',
    'institute', 'int', 'international', 'iq', 'ir', 'is', 'it', 'je', 'jobs', 'jp', 'kaufen', 'ke', 'kg', 'ki', 'care',
    'kitchen', 'kiwi', 'koeln', 'kr', 'kz', 'la', 'land', 'lease', 'li', 'lighting', 'limo', 'link', 'london', 'football',
    'lt', 'lu', 'luxury', 'lv', 'ly', 'ma', 'management', 'mango', 'marketing', 'md', 'me', 'media', 'menu', 'mg', 'tours',
    'miami', 'mk', 'ml', 'mn', 'mo', 'mobi', 'moda', 'monash', 'mp', 'ms', 'mu', 'museum', 'mx', 'my', 'na', 'name', 'tube',
    'nc', 'nf', 'ng', 'ninja', 'nl', 'no', 'nu', 'nz', 'om', 'onl', 'paris', 'partners', 'parts', 'pe', 'pf', 'financial',
    'photo', 'photography', 'photos', 'pics', 'pictures', 'pl', 'plumbing', 'pm', 'post', 'pr', 'pro', 'productions',
    'properties', 'pt', 'pub', 'pw', 'qa', 'quebec', 're', 'recipes', 'reisen', 'rentals', 'repair', 'report', 'app',
    'rest', 'reviews', 'rich', 'ro', 'rocks', 'rodeo', 'rs', 'ru', 'ruhr', 'sa', 'saarland', 'sb', 'sc', 'se', 'icu',
    'services', 'sexy', 'sg', 'sh', 'shoes', 'si', 'singles', 'sk', 'sm', 'sn', 'so', 'social', 'solar', 'solutions',
    'soy', 'st', 'su', 'supplies', 'supply', 'support', 'sx', 'sy', 'systems', 'tattoo', 'tc', 'technology', 'tel',
    'tf', 'th', 'tienda', 'tips', 'tk', 'tl', 'tm', 'tn', 'to', 'today', 'tools', 'town', 'toys', 'tr', 'training',
    'travel', 'tv', 'tw', 'tz', 'ua', 'ug', 'uk', 'university', 'us', 'uy', 'black', 'blue', 'info', 'kim', 'pink',
    'red', 'shiksha', 'uz', 'vacations', 'vc', 've', 'vegas', 'ventures', 'vg', 'viajes', 'villas', 'vision', 'vodka',
    'voting', 'voyage', 'vu', 'wang', 'watch', 'wed', 'wf', 'wien', 'wiki', 'works', 'ws', 'xxx', 'xyz', 'yt', 'za',
    'zm', 'zone', 'dj', 'do', 'eg', 'eh', 'er', 'et', 'fj', 'fk', 'fm', 'gallery', 'gb', 'ge', 'gf', 'gh', 'gm', 'xin',
    'gn', 'gp', 'gq', 'gr', 'gt', 'gu', 'gw', 'hm', 'jetzt', 'jm', 'jo', 'kh', 'km', 'kn', 'kp', 'kred', 'kw', 'ky',
    'lb', 'lk', 'lr', 'ls', 'mc', 'mf', 'mh', 'mil', 'mm', 'moe', 'mq', 'mr', 'mt', 'mv', 'mw', 'mz', 'nagoya', 'ne',
    'neustar', 'ni', 'np', 'nr', 'nyc', 'okinawa', 'pa', 'pg', 'ph', 'pk', 'pn', 'ps', 'py', 'qpon', 'ren', 'rw', 'krd',
    'sd', 'sj', 'sl', 'sohu', 'sr', 'ss', 'sv', 'sz', 'td', 'tg', 'tj', 'tokyo', 'tp', 'trade', 'tt', 'um', 'uno', 'llc',
    'va', 'vi', 'vi', 'vn', 'webcam', 'ye', 'yokohoma', 'ryukyu', 'meet', 'vote', 'lc', 'voto', 'wed', 'zw', 'ooo', 'ltda',
    'stream', 'wtf', 'observer', 'site', 'tech', 'world', 'vet', 'video', 'vin', 'website', 'wedding', 'whoswho', 'win',
    'wine', 'work', 'yoga', 'tires', 'tickets', 'theatre', 'theater', 'tennis', 'team', 'taxi', 'tax', 'surgery', 'surf',
    'sucks', 'study', 'style', 'storage', 'studio', 'space', 'software', 'soccer', 'ski', 'show', 'shopping', 'shop',
    'security', 'science', 'schule', 'school', 'sarl', 'salon', 'sale', 'run', 'rip', 'review', 'restaurant', 'republican',
    'rent', 'reise', 'rehab', 'realty', 'racing', 'protection', 'property', 'promo', 'press', 'plus', 'place', 'pizza',
    'pet', 'party', 'organic', 'one', 'news', 'network', 'navy', 'movie', 'mortgage', 'money', 'mom', 'men', 'memorial',
    'mba', 'market', 'maison', 'love', 'lol', 'loan', 'live', 'limited', 'life', 'lgbt', 'legal', 'lawyer', 'juegos',
    'jewelry', 'irish', 'investments', 'insure', 'ink', 'hosting', 'host', 'hospital', 'hockey', 'hiv', 'hiphop', 'help',
    'healthcare', 'guide', 'group', 'green', 'gratis', 'golf', 'gold', 'gmbh', 'global', 'gives', 'gifts', 'garden', 'games',
    'game', 'fyi', 'furniture', 'fund', 'forsale', 'flowers', 'fitness', 'fit', 'finance', 'film', 'fashion', 'fans', 'family',
    'faith', 'fail', 'express', 'exchange', 'engineer', 'energy', 'earth', 'download', 'doctor', 'discount', 'direct',
    'digital', 'diet', 'design', 'dentist', 'dental', 'delivery', 'degree', 'deals', 'date', 'dance', 'cricket', 'creditcard',
    'credit', 'courses', 'coupons', 'condos', 'consulting', 'coach', 'cloud', 'clinic', 'click', 'claims', 'city', 'church',
    'chat', 'charity', 'casino', 'cafe', 'buzz', 'business', 'boston', 'blog', 'bio', 'bingo', 'bid', 'beer', 'band', 'audio',
    'auction', 'attorney', 'art', 'army', 'apartments', 'airforce', 'accountants', 'accountant'
];
